import type { CityConfig } from '@/types/city'

export const CHARLOTTE: CityConfig = {
  key: 'charlotte',
  displayName: 'Charlotte',
  state: 'NC',
  socrataHost: 'https://data.charlottenc.gov',
  datasets: {
    complaints311: {
      type: 'arcgis',
      url: 'https://gis.charlottenc.gov/arcgis/rest/services/ODP/ServiceRequests311/MapServer/0',
      pageSize: 500,
    },
    permits: {
      type: 'arcgis',
      url: 'https://meckgis.mecklenburgcountync.gov/server/rest/services/BuildingPermits/FeatureServer/0',
      where: "taxjuris = 'CHARLOTTE'",
      pageSize: 500,
    },
    inspections: {
      type: 'charlotte-health-inspections',
      baseUrl: 'https://public.cdpehs.com/NCENVPBL/ESTABLISHMENT/ShowESTABLISHMENTTablePage.aspx?ESTTST_CTY=60',
      cityFilter: 'CHARLOTTE',
      maxRecords: 250,
    },
    budget: {
      type: 'pdf-budget',
      url: 'https://www.charlottenc.gov/files/sharedassets/city/v/1/city-government/departments/documents/budget/fy2026/adopted-fy2026-budget.pdf',
      fiscalYear: 2026,
      parser: 'charlotte-adopted-fy2026',
    },
    representatives: {
      type: 'arcgis',
      url: 'https://gis.charlottenc.gov/arcgis/rest/services/PLN/CouncilDistricts/MapServer/0',
      pageSize: 20,
    },
    wardBoundaries: {
      type: 'arcgis',
      url: 'https://gis.charlottenc.gov/arcgis/rest/services/PLN/CouncilDistricts/MapServer/0',
      pageSize: 20,
    },
  },
  fields: {
    districtCol: 'COUNCIL_DISTRICT',
    boundaryDistrict: 'District',
    srNumber: 'REQUEST_NO',
    srType: 'REQUEST_TYPE',
    srCreatedDate: 'RECEIVED_DATE',
    srAddress: 'FULL_ADDRESS',
    srLat: 'LATITUDE',
    srLng: 'LONGITUDE',
    permitId: 'permitnum',
    permitNumber: 'permitnum',
    permitType: 'permitdesc',
    permitIssueDate: 'issuedate',
    permitAddress: 'projadd',
    permitDescription: 'workdesc',
    permitExpandedDescription: 'permitdesc',
    permitExpandedDescriptionFallbacks: ['projname', 'projdesc', 'worktype', 'typeofbldg', 'workdesc'],
    permitFee: 'bldgcost',
    permitContact: 'ownname',
    inspectionId: 'inspection_id',
    inspectionName: 'dba_name',
    inspectionDate: 'inspection_date',
    inspectionType: 'inspection_type',
    inspectionResult: 'inspection_result',
    inspectionViolations: 'inspection_notes',
    inspectionAddress: 'address',
    inspectionZip: 'zip',
    inspectionRisk: 'risk',
    inspectionLat: 'latitude',
    inspectionLng: 'longitude',
    repDistrict: 'District',
    repName: 'DistrictRep',
    repEmail: 'RepEmail',
  },
  councilBodyName: 'City Council',
  agendaProvider: {
    type: 'legistar-matters',
    client: 'charlottenc',
    detailBaseUrl: 'https://charlottenc.legistar.com',
    bodyName: 'City Council',
    staleAfterDays: 180,
    maxItems: 12,
    hydratePublicSourceFromSearch: true,
    excludeMatterTypes: [
      'Budget Workshop',
      'Strategy Session',
      'Committee Item',
      'Workshop Item',
      'Special Meeting Item',
      'Nomination',
      'Reference',
      'Action Review',
      'Awards and Recognitions',
      'Public Forum',
    ],
    excludeTitlePatterns: [
      'city manager',
      'reference - ',
      'closed session',
      'public forum',
      'awards and recognitions',
      'action review',
    ],
    maxAgendaLeadDays: 45,
  },
  districtName: 'District',
  districtCount: 7,
  timezone: 'America/New_York',
  center: [35.2271, -80.8431],
  defaultZoom: 11,
  geocoder: 'arcgis',
  geocoderSource: {
    type: 'arcgis',
    url: 'https://gis.charlottenc.gov/arcgis/rest/services/LOC/MasterAddress/GeocodeServer',
    citySuffix: 'Charlotte, NC',
    maxLocations: 1,
    minScore: 80,
  },
}
