import type { CityConfig } from '@/types/city'

export const CHICAGO: CityConfig = {
  key: 'chicago',
  displayName: 'Chicago',
  state: 'IL',
  socrataHost: 'https://data.cityofchicago.org',
  datasets: {
    complaints311: 'v6vf-nfxy',
    permits: 'ydr8-5enu',
    inspections: '4ijn-s7e5',
    budget: '6694-f78c',
    budgetAlts: ['t59y-fr3k', 'x394-e874'],
    representatives: 'htai-wnw4',
    wardBoundaries: 'p293-wvbd',
  },
  fields: {
    // 311
    districtCol: 'ward',
    srNumber: 'sr_number',
    srType: 'sr_type',
    srStatus: 'status',
    srCreatedDate: 'created_date',
    srClosedDate: 'closed_date',
    srAddress: 'street_address',
    srLat: 'latitude',
    srLng: 'longitude',
    // Permits
    permitId: 'id',
    permitNumber: 'permit_',
    permitType: 'permit_type',
    permitIssueDate: 'issue_date',
    permitAddressParts: ['street_number', 'street_direction', 'street_name'],
    permitDistrict: 'ward',
    permitDescription: 'work_description',
    permitFee: 'total_fee',
    permitLat: 'latitude',
    permitLng: 'longitude',
    permitContact: 'contact_1_name',
    // Inspections — no district col (uses spatial query)
    inspectionId: 'inspection_id',
    inspectionName: 'dba_name',
    inspectionDate: 'inspection_date',
    inspectionType: 'inspection_type',
    inspectionResult: 'results',
    inspectionViolations: 'violations',
    inspectionAddress: 'address',
    inspectionZip: 'zip',
    inspectionRisk: 'risk',
    inspectionLat: 'latitude',
    inspectionLng: 'longitude',
    // Budget
    budgetDepartment: 'department_description',
    budgetAmount: '_ordinance_amount_',
    // Representatives
    repDistrict: 'ward',
    repName: 'alderman',
    repPhone: 'ward_phone',
    repEmail: 'email',
    repWebsite: 'website',
    repAddress: 'city_hall_address',
    repPhoto: 'photo_link',
  },
  councilBodyName: 'City Council',
  agendaProvider: {
    type: 'chicago-elms',
    apiBaseUrl: 'https://api.chicityclerkelms.chicago.gov',
    detailBaseUrl: 'https://chicityclerkelms.chicago.gov/',
    filter: 'supersededBy eq null',
    sort: 'lastPublicationDate desc',
    maxItems: 12,
  },
  districtName: 'Ward',
  districtCount: 50,
  timezone: 'America/Chicago',
  center: [41.8827, -87.6233],
  defaultZoom: 11,
  geocoder: 'chicago-arcgis',
}
