import type { CityConfig } from '@/types/city'

export const RALEIGH: CityConfig = {
  key: 'raleigh',
  displayName: 'Raleigh',
  state: 'NC',
  socrataHost: 'https://data.raleighnc.gov',
  datasets: {
    complaints311: {
      type: 'arcgis',
      url: 'https://services.arcgis.com/v400IkDOw1ad7Yad/ArcGIS/rest/services/Ask_Raleigh_Requests/FeatureServer/0',
      pageSize: 500,
    },
    permits: {
      type: 'arcgis',
      url: 'https://services.arcgis.com/v400IkDOw1ad7Yad/ArcGIS/rest/services/Building_Permits/FeatureServer/0',
      pageSize: 500,
    },
    inspections: {
      type: 'arcgis',
      url: 'https://services.arcgis.com/v400IkDOw1ad7Yad/ArcGIS/rest/services/Inspection_Schedule_Public/FeatureServer/0',
      pageSize: 500,
    },
    budget: {
      type: 'pdf-budget',
      url: 'https://cityofraleigh0drupal.blob.core.usgovcloudapi.net/drupal-prod/COR11/fy26-adopted-budget.pdf',
      fiscalYear: 2026,
      parser: 'raleigh-adopted-fy2026',
    },
    representatives: {
      type: 'arcgis',
      url: 'https://services.arcgis.com/v400IkDOw1ad7Yad/ArcGIS/rest/services/Raleigh_City_Council_Districts/FeatureServer/0',
      pageSize: 20,
    },
    wardBoundaries: {
      type: 'arcgis',
      url: 'https://services.arcgis.com/v400IkDOw1ad7Yad/ArcGIS/rest/services/Raleigh_City_Council_Districts/FeatureServer/0',
      pageSize: 20,
    },
  },
  fields: {
    boundaryDistrict: 'COUNCIL_DI',
    srNumber: 'NUMBER',
    srType: 'REQUEST_TYPE',
    srTypeFallbacks: ['SERVICE', 'CATEGORY'],
    srStatus: 'STATUS',
    srCreatedDate: 'APPLIED_DATE',
    srClosedDate: 'CLOSED_AT',
    srAddress: 'ADDRESS',
    permitId: 'permitnum',
    permitNumber: 'permitnum',
    permitType: 'permittypemapped',
    permitIssueDate: 'issueddate',
    permitAddressParts: ['streetnum', 'streetdirectionprefix', 'streetname', 'streettype', 'streetdirectionsuffix'],
    permitDescription: 'proposedworkdescription',
    permitDescriptionFallbacks: ['description'],
    permitExpandedDescription: 'proposedworkdescription',
    permitExpandedDescriptionFallbacks: ['perm_comments', 'reviewercomments', 'description'],
    permitFee: 'estprojectcost',
    permitLat: 'latitude_perm',
    permitLng: 'longitude_perm',
    permitContact: 'contractorcompanyname',
    inspectionId: 'OBJECTID',
    inspectionDate: 'Scheduled',
    inspectionAddress: 'Address',
    repDistrict: 'COUNCIL_DI',
    repName: 'COUNCIL_PE',
  },
  councilBodyName: 'City Council',
  agendaProvider: {
    type: 'escribe',
    baseUrl: 'https://pub-raleighnc.escribemeetings.com/?FillWidth=1',
    lookbackDays: 180,
    maxItems: 12,
    maxMeetings: 3,
    meetingTypeKeywords: ['City Council'],
  },
  districtName: 'District',
  districtCount: 5,
  districtLabels: {
    1: 'A',
    2: 'B',
    3: 'C',
    4: 'D',
    5: 'E',
  },
  timezone: 'America/New_York',
  center: [35.7796, -78.6382],
  defaultZoom: 11,
  geocoder: 'nominatim',
  geocoderConfig: { countrycodes: 'us', viewbox: '-78.82,35.70,-78.49,35.92' },
}
